# Generated by Django 5.0.4 on 2024-05-14 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentfeedbackmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectA.makeproductmodel'),
        ),
        migrations.AlterField(
            model_name='makeproductmodel',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='makeproductmodel',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='makeproductmodel',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='makeproductmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='ProjectA/images_products/'),
        ),
    ]
