# Generated by Django 5.0.4 on 2024-05-26 16:36

import ProjectA.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectA', '0002_commentfeedbackmodel_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeproductmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=ProjectA.models.get_upload_path),
        ),
    ]
