services:
  django: 
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/dj_map
    ports:
      - 8000:8000
    environment:
      - DEBAG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A core worker -l INFO
    volumes:
      - .:/dj_map
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - django
      - redis

  redis:
    image: "redis:alpine"
  
  beat:
    build: .
    volumes:
      - .:/dj_map
    depends_on:
      - redis
      - django
      - celery
    command: 'celery -A dj_map beat -l info'
    




